### ISSUE TITLE
Enemy check treats allied factions as enemies

### ISSUE THREAD

**Issue by kontu** [BobDaRoss/QuantumHangar#10]
When trying to !hangar save or load a grid, the enemy detection radius seems to be including factions you are allied with in game ("Peace") as "enemies" and prevents using the hangar

**Comment by BobDaRoss** [comment]
It will ignore allies now

**Comment by kontu** [comment]
As of Sept 19th players still reported not being able to load from hangar if an allied faction is nearby

**Comment by BobDaRoss** [comment]
Pretty sure this has been fixed. Just need to update it
