### ISSUE TITLE
Saving multiple grids with identical name can at least sometimes lead to the duplicate renaming not working

### ISSUE THREAD

**Issue by kontu** [BobDaRoss/QuantumHangar#14]
https://i.imgur.com/L2Ah5lN.png
https://i.imgur.com/lcXpJCt.png

Saved 5 copies of "DirksFavoriteHat"; all past the first got appended with [1]. I would have expected [1], [2], [3], etc to avoid dupe names

**Comment by BobDaRoss** [comment]
Fixed
