### ISSUE TITLE
[Bug] player sent to spectator mode

### ISSUE THREAD

**Issue by MisterRee** [BobDaRoss/QuantumHangar#2]
**Expected Behaviour:** When a player uses the `!hangar save` command on a grid, any player in a seat should be kicked from that seat when the grid is stored.

**Actual Behaviour:** When a player uses the `!hangar save` command on a grid, any player in a seat is sent to spectator mode and must relog to return to character control.

Behaviour replicated in `Flight Seat`, `Control Seat`, `Passenger Seat`, `Toilet Seat`, `Fighter Cockpit`, `Industrial Cockpit` and `Cockpit`.

**Comment by BobDaRoss** [comment]
Issue has been fixed
