### ISSUE TITLE
"Enable Plugin" Checkbox unchecked, autohangar still occurred

### ISSUE THREAD

**Issue by kontu** [BobDaRoss/QuantumHangar#6]
Had the plugin installed but the main "Hangar Config" had "Enable Plugin" unchecked
https://i.imgur.com/qITTTPB.png

That made me think nothing from QH would be accessible / run

Buuut I had left Autohangar configured to nab things >30% below surface
https://i.imgur.com/NYLocy6.png

and a grid got snatched up by QH and confused the hell out of me

**Comment by BobDaRoss** [comment]
hmmm
