### ISSUE TITLE
Grids being removed from hangar as dupes when they aren't

### ISSUE THREAD

**Issue by kontu** [BobDaRoss/QuantumHangar#8]
We're having grids removed from player hangars by the anti-dupe protection that aren't dupes
Fastest way to reproduce:
Print a blueprint with a welder with the name "Sausage"
!hangar save
Print a second copy with the name "Sausage" (so just use the same blueprint)

The player now has a copy in the Hangar and an "identical" copy in the world -- Hangar removes it from the Hangar;  but leaves it in the players hangar list. They try to !hangar load it and get told "grid doesn't exist have admin check logs"

**Comment by kontu** [comment]
Excerpt from logs: Player had printed a second "Field Marshal[1]" while having one in their hangar already 
Their copy in the Hangar got removed and they had a bunk entry in their !hangar list they could no longer load.
We ended up restoring from gridbackup

```07:42:37.4390 [WARN]   QuantumHangar.Utilities.GridTracker: Server succesfully saved with grid Field Marshal in hangar! Clearing ID!
07:42:37.4390 [WARN]   QuantumHangar.Utilities.GridTracker: Server Successfully saved with Field Marshal[1] loaded in server! Deleting sbc!
07:42:37.4390 [WARN]   QuantumHangar.Utilities.GridTracker: Server succesfully saved with grid Utility Vehicle in hangar! Clearing ID!
07:42:37.4390 [WARN]   QuantumHangar.Utilities.GridTracker: Deleted Hangar Files via GridTracker!
```

**Comment by BobDaRoss** [comment]
Removed HangarDupePrevention and Fixed GridNaming
